---
title: "p8106_final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE,messages=FALSE)
library(tidyverse)
library(EnvStats)
library(earth)
library(caret)
library(pROC)
library(visdat)
library(vip)
```

```{r}
# Read in the data
income_df = read.csv("adult.csv") %>% 
  mutate_all(list(~gsub("\\?", NA, .))) 
```

```{r}
# generate missing data visualization 
vis_miss(income_df)
```

```{r}
# recoding and grouping categories
# 1. rename income variables
# 2. categorize workclass into gov,self_emp, private
# 3. merge marital status into married
# 4. merge occupation into MBSA/Service/NCM/PTM
# 5. merge native countries into US/Others
income_df <- income_df %>% 
  mutate(income = recode(income, "<=50K" = "le50k", ">50K" = "g50k")) %>% 
  mutate(workclass = ifelse(workclass %in% c("State-gov", "Federal-gov", "Local-gov"), "Gov", workclass),
         workclass = ifelse(workclass %in% c("Self-emp-not-inc", "Self-emp-inc"), "Self-emp", workclass),
         marital.status = ifelse(marital.status %in% c("Married-civ-spouse", "Married-spouse-absent", "Married-AF-spouse"), "Married", marital.status),
         occupation = ifelse(occupation %in% c("Exec-managerial", "Adm-clerical", "Prof-specialty", "Tech-support"), "MBSA", occupation),
         occupation = ifelse(occupation %in% c("Handlers-cleaners", "Protective-serv", "Priv-house-serv", "Other-service"), "Service", occupation),
         occupation = ifelse(occupation %in% c("Craft-repair", "Farming-fishing", "Machine-op-inspct"), "NCM", occupation),
         occupation = recode(occupation, "Transport-moving" = "PTM"),
         native.country = ifelse(native.country != "United-States", "Others", "US"))

# Grouping "education" category: below-HS, HS-grad, Asso-prof-grad, Some College, Bachelors-and-above
income_df = income_df %>%
   mutate(education = ifelse(education %in% c("1st-4th","5th-6th","7th-8th","9th","10th","11th","12th","Preschool"),"Below-HS", education),
         education = ifelse(education %in% c("Assoc-acdm", "Assoc-voc","Prof-school"), "Asso-prof-grad", education),
         education = ifelse(education %in% c("Bachelors","Masters","Doctorate"),"Bachelor-and-above",education))

# recode capital gain into category (optional)
income_df = income_df %>% 
  mutate(capital.gain.bi = capital.gain)%>%
  mutate(capital.gain.bi = case_when(
      capital.gain.bi == 0 ~ "no-gain",
      capital.gain.bi != 0 ~ "positive-gain" ))

# recode capital loss into category (optional)
income_df = income_df %>% 
  mutate(capital.loss.bi = capital.loss)%>%
  mutate(capital.loss.bi = case_when(
      capital.loss.bi == 0 ~ "no-loss",
      capital.loss.bi != 0 ~ "positive-loss" ))

# recode hours.per.week into categories (optional)
income_df = income_df %>% 
  mutate(hours.per.week.lv = as.integer(hours.per.week))%>%
  mutate(hours.per.week.lv = case_when(
      hours.per.week.lv < 40 ~ "part-time",
      hours.per.week.lv == 40 ~ "full-time",
      hours.per.week.lv > 40  ~ "over-time"))
```

```{r}
# recode continuous variables capital.gain, capital.loss using log transformation
income_df = income_df %>%
  mutate(capital.gain = as.numeric(capital.gain)) %>%
  mutate(
    capital.gain = log1p(capital.gain)
  ) %>%
  mutate(capital.loss = as.numeric(capital.loss)) %>%
  mutate(
    capital.loss = log1p(capital.loss)
  )
```

```{r} 
# Remove NA as well as small categories
income_df = income_df %>% 
  drop_na() %>% 
  filter(workclass != "Without-pay") %>% 
  filter(occupation != "Armed-Forces")%>%
  select(-fnlwgt)

# convert the dataframe into the right format for continuous/categorical variables
income_df <- income_df %>% 
  mutate_all(list(~gsub("\\-", "_", .))) %>% 
  mutate_at(vars(age, education.num, capital.gain,capital.loss,hours.per.week), 
            list(as.numeric)) %>% 
  mutate_at(vars(workclass, marital.status, occupation,education,relationship, race, sex, native.country,capital.gain.bi,capital.loss.bi,hours.per.week.lv, income),
            list(factor)) %>% 
  relocate(age, education.num, capital.gain, capital.loss, hours.per.week,capital.gain.bi,capital.loss.bi,hours.per.week.lv,everything())
```

```{r}
# remove capital.gain, capital.loss,hours.per.week.lv
income_df = income_df %>% select(-c(hours.per.week.lv, capital.gain.bi, capital.loss.bi, education))
income_df
```

```{r continuous, fig.align='center'}
cont_df = income_df %>% 
  select(age, education.num, capital.gain,
         capital.loss, hours.per.week, income) %>% 
  pivot_longer(age:hours.per.week,
               names_to = "predictors",
               values_to = "value")
cont_df %>% 
  ggplot(aes(x = predictors, y = value, fill = income)) +
  geom_boxplot() +
  facet_wrap(.~predictors, scales = "free", nrow = 3) +
  labs(x = "Predictors",
       y = "Value")
```

```{r discrete, fig.align='center'}
discrete_df = 
  income_df %>% 
  select_if(is.factor) %>% 
  pivot_longer(workclass:native.country,
               names_to = "predictors",
               values_to = "value") %>% 
  group_by(income, predictors) %>% 
  count(value)

discrete_df %>% 
  ggplot(aes(x = value, y = n, fill = income)) +
  geom_bar(position=position_dodge(), stat="identity") +
  facet_wrap(.~predictors, scales = "free", nrow = 3) +
  theme(axis.text.x = element_text(angle = 20, hjust=1)) +
  labs(x = "Predictors",
       y = "Total count")
```

```{r partition}
# turn categorical variables into dummy variables
income2 = model.matrix(income ~ ., income_df)[ ,-1]

set.seed(23)
rowTrain = createDataPartition(y = income_df$income,
                                p = 0.7,
                                list = FALSE)
# matrix of predictors
x = income2[rowTrain,]
# vector of response
y = income_df$income[rowTrain]

# training control
ctrl = trainControl(method = "cv", number = 10, 
                    summaryFunction = twoClassSummary,
                    classProbs = TRUE)

```

```{r}
corrplot::corrplot(cor(x), method = "square",type="upper")
```

```{r glm, cache = TRUE}
set.seed(23)
model.glm <- train(x = x,
                   y = y,
                   method = "glm",
                   trControl = ctrl, 
                   metric = "ROC")

glmnGrid <- expand.grid(.alpha = seq(0, 1, length = 6),
                        .lambda = exp(seq(-11, -3, length = 20)))
set.seed(23)
model.glmn <- train(x = x,
                    y = y,
                    method = "glmnet",
                    tuneGrid = glmnGrid,
                    metric = "ROC", 
                    trControl = ctrl)

#plot(model.glmn, xTrans = function(x) log(x)) 
```

```{r lda_qda, cache = TRUE}
set.seed(23)
model.lda <- train(x = x,
                   y = y,
                   method = "lda",
                   metric = "ROC",
                   trControl = ctrl)

set.seed(23)
model.qda <- train(x = x,
                   y = y,
                   method = "qda",
                   metric = "ROC",
                   trControl = ctrl)
```

```{r mars, cache = TRUE}
mars_grid = expand.grid(degree = 1:3, nprune = 2:30)

set.seed(23)
model.mars = train(x = x, 
                 y = y,
                 method = "earth",
                 tuneGrid = mars_grid,
                 metric = "ROC",
                 trControl = ctrl)

# ggplot(model.mars, highlight = TRUE)
```

```{r random forest, cache =TRUE}
rf.grid <- expand.grid(mtry = 1:8, splitrule = "gini",min.node.size = seq(from = 2, to = 10, by = 2))

set.seed(1)
rf.fit = train(x = x,
               y = y,
              method = "ranger",
              tuneGrid = rf.grid,
              metric = "ROC", 
              trControl = ctrl)


ggplot(rf.fit, highlight = TRUE)

```

```{r boosting, cache = TRUE}
gbmA.grid = expand.grid(n.trees = c(2000,3000,4000), 
                        interaction.depth = 1:6,
                        shrinkage = c(0.001,0.003,0.005), 
                        n.minobsinnode = 1)
set.seed(25)
gbmA.fit <- train(x = x ,
                  y = y,
                  tuneGrid = gbmA.grid,
                  trControl = ctrl,
                  method = "gbm",
                  distribution = "adaboost",
                  metric = "ROC",
                  verbose = FALSE)

ggplot(gbmA.fit, highlight = TRUE)

```

```{r resample}
res <- resamples(list(MARS = model.mars,
                      GLM = model.glm,
                      GLMNET = model.glmn,
                      LDA = model.lda,
                      QDA = model.qda,
                      RF = rf.fit,
                      GBMA = gbmA.fit))
summary(res)
```

```{r test_perf, cache = TRUE}

# performance with test data set 
glm.pred = predict(model.glm, newdata = income2[-rowTrain,], type = "prob")[,2]
glmn.pred = predict(model.glmn, newdata = income2[-rowTrain,], type = "prob")[,2]
lda.pred = predict(model.lda, newdata = income2[-rowTrain,], type = "prob")[,2]
qda.pred = predict(model.qda, newdata = income2[-rowTrain,], type = "prob")[,2]
mars.pred = predict(model.mars, newdata = income2[-rowTrain,], type = "prob")[,2]
rf.pred = predict(rf.fit, newdata = income2[-rowTrain,], type = "prob")[,1]
gbmA.pred = predict(gbmA.fit, newdata = income2[-rowTrain,], type = "prob")[,1]

# ROCs
roc.glm = roc(income_df$income[-rowTrain], glm.pred)
roc.glmn = roc(income_df$income[-rowTrain], glmn.pred)
roc.lda = roc(income_df$income[-rowTrain], lda.pred)
roc.qda = roc(income_df$income[-rowTrain], qda.pred)
roc.mars = roc(income_df$income[-rowTrain], mars.pred)
roc.rf = roc(income_df$income[-rowTrain], rf.pred)
roc.gbmA = roc(income_df$income[-rowTrain], gbmA.pred)

# AUCs
auc <- c(roc.glm$auc[1], roc.glmn$auc[1], roc.lda$auc[1], roc.qda$auc[1], 
         roc.mars$auc[1], roc.rf$auc[1], roc.gbmA$auc[1])

# AUC plot
plot(roc.glm, legacy.axes = TRUE)
plot(roc.glmn, col = 2, add = TRUE)
plot(roc.lda, col = 3, add = TRUE)
plot(roc.qda, col = 4, add = TRUE)
plot(roc.mars, col = 5, add = TRUE)
plot(roc.rf, col = 6, add = TRUE)
plot(roc.gbmA, col = 7, add = TRUE)
modelNames = c("glm", "glmn", "lda","qda", "mars", "rf", "gbmA")
legend("bottomright", legend = paste0(modelNames, ": ", round(auc,3)),
       col = 1:7, lwd = 2, cex = 0.8)
```

```{r vip}
# variable importance 
vip(gbmA.fit$finalModel) + ggtitle("Gradient Boosting")
```

